import { StyleSheet } from "react-native";

export const globalStyle = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FFF",
    },
    backImage: {
        width: "100%",
        height: "100%",
        position: "absolute",
        top: 0,
        resizeMode: "cover",
    },
    button: {
        backgroundColor: '#0e628c',
        height: 58,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
      },
      buttonCS: {
        backgroundColor: "#3e48a0",
        height: 50,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: 'center',
        marginTop: 5,
      },
    input: {
        backgroundColor: "#bfd5ff",
        height: 58,
        marginBottom: 20,
        fontSize: 16,
        borderRadius: 10,
        padding: 12,
    },
    title: {
        fontSize: 36,
        fontWeight: 'bold',
        color: "#ec7517",
        alignSelf: "center",
        paddingBottom: 24,
    },
    titleNote: {
      fontSize: 25,
      fontWeight: 'bold',
      alignSelf: 'flex-start', 
      padding: 5,
      color: '#ea7f2c',
    },
    form: {
        flex: 1,
        justifyContent: 'center',
        marginHorizontal: 30,
      },
      whiteSheetSU: {
        width: "100%",
        height: "63%",
        position: 'absolute',
        bottom: 0,
        backgroundColor: '#ffecd9',
        borderRadius: 60,
        marginBottom: "30%",
      },
      containerNotes: {
        backgroundColor: 'rgba(255, 213, 153, 0.5)',
        marginBottom: 30,
        borderColor: '#ffad5b',
        borderWidth: 2,
        borderRadius: 5,
      },
      containerParadas: {
        backgroundColor: 'rgba(182, 189, 245, 0.5)',
        marginBottom: 15,
        borderColor:'#505fe5',
        borderWidth: 3,
        borderRadius: 8,
      },
      containerBus: {
        borderColor: '#ffad5b',
        marginBottom: -2,
        borderWidth: 2,
        borderRadius: 5,
        width: "35%"
      },
      titleParada: {
        fontSize: 18,
        fontWeight: 'bold',
        alignSelf: 'center', 
        marginBottom: 60,
        color: '#e3791b',
      },
      textoInfo: {
        fontSize: 16,
        alignSelf: 'flex-start',
        marginBottom: 60, 
        color: "#c98528",
      },
      imgBus: {
        width: 28,
        height: 28,
        alignSelf: 'center',
        position: 'absolute',
        top: 0,
      },
});